#
# Copyright (c) 2016 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

# STEP 2 - Enable the I2C driver
CONFIG_I2C=y
# STEP 4.2 - Enable floating point format specifiers
CONFIG_CBPRINTF_FP_SUPPORT=y

# Shorten I2C transfer timeout so waveforms appear more frequently
# when no slave is connected (default is 500 ms)
CONFIG_I2C_NRFX_TRANSFER_TIMEOUT=10

# Disable device runtime PM to force TWIM stay active after init
CONFIG_PM_DEVICE_RUNTIME=n

